/// <reference types="react-scripts" />
declare module "cytoscape-cose-bilkent"
declare module "cytoscape-cola"
declare module "cytoscape-dagre"
declare module "cytoscape-euler"
declare module "cytoscape-avsdf"
declare module "cytoscape-cise"
declare module "react-cytoscapejs"
declare module "cytoscape-undo-redo"
declare module "cytoscape-cxtmenu"
declare module "cytoscape-edgehandles"
declare module "cytoscape-d3-force"
declare module "cytoscape-fcose"
declare module "cytoscape-popper"
declare module "cytoscape-ngraph.forcelayout"
declare module "cytoscape-elk"
declare module "html2canvas"
